version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: geocoding-postgres
    environment:
      POSTGRES_DB: base
      POSTGRES_USER: base
      POSTGRES_PASSWORD: base
    ports:
      - "5432:5432"
